config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => 'signup'}
  
  resources :users
  root to: 'posts#index'
  
  namespace :admin do
    resources :posts do
      put :toggle_state, on: :member
    end
  end
  resources :comments

  resources :posts, path: ''

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments
	default_scope { where('deleted != true')}
	def to_param
		permalink
	end

	before_save :set_permalink
	def set_permalink
		self.permalink = title.parameterize
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  include ::ActionView::Layouts
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_state]
  before_action :authenticate_user
  layout 'admin'
  def index
    @posts = Post.order('created_at DESC').all
    @props = @posts.map do |post|
      {
        title: post.title,
        body: post.body,
        created_at: post.created_at,
        id: post.id,
        post_url: admin_post_path(post),
        destroy_url: admin_post_path(post),
        state: post.state,
        toggle_state_url: toggle_state_admin_post_path(post),
        preview_url: post_path(post)

      }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: {title: @post.title, body: @post.body}}
    end 
  end


  def new
    @post = Post.new
  end


  def edit
  end


  def update
    
    if @post.update(post_params)
      render json: {
          title: @post.title,
          body: @post.body,
          created_at: @post.created_at,
          id: @post.id,
          post_url: admin_post_path(@post),
          destroy_url: admin_post_path(@post),
          state: @post.state,
          toggle_state_url: toggle_state_admin_post_path(@post),
          preview_url: post_path(@post)
        }.to_json
    end
  end


  def destroy
    id = @post.id
    @post.update_attribute(:deleted, true)
    render json: {id: id}
  end

  def toggle_state
    if @post.update_attribute(:state, 
        @post.state == 'published' ? 'draft' : 'published'
      )
      render json: {id: @post.id, state: @post.state}
    end
  end

  def create
    @post = Post.new(post_params)
      if @post.save
        render json: {
          title: @post.title,
          body: @post.body,
          created_at: @post.created_at,
          id: @post.id,
          post_url: admin_post_path(@post),
          destroy_url: admin_post_path(@post),
          state: @post.state,
          toggle_state_url: toggle_state_admin_post_path(@post),
          preview_url: post_path(@post)
        }.to_json

      else
        render nothing: true, status: 422
      end
    end
  end



  private

    def authenticate_user
      if current_user.try(:usertype) == 'admin'
        authenticate_user!
      else
        redirect_to root_path
      end
    end

    def set_post
      @post = Post.where(permalink: params[:id]).first
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
      if resource.usertype == 'admin'
      	admin_posts_path
      else
      	root_path
      end
    end
  
    

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:login, :email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create

		@comment = Comment.new(post_params)
		@comment.user_id = current_user.id
		if @comment.save
			render nothing: true, head: :ok
		else
			render nothing: true, status: 422
		end
	end
	

	private

	def post_params
		params.require(:comment).permit(:text, :post_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'digest/md5'
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.where(state: 'published').order('created_at DESC').all
    @props = @posts.map do |post|
      {
        created_at: post.created_at.strftime('%d %B %Y'),
        title: post.title,
        body: post.body,
        comments: comments_for(post),
        comments_url: comments_url,
        id: post.id,
        signed_in: current_user.present?,
        gravathar: current_user.present? ? gravathar(current_user.email) : '',
        post_url: post_path(post)
      }
    end
  end


  def show
    @props = {
        created_at: @post.created_at.strftime('%d %B %Y'),
        title: @post.title,
        body: @post.body,
        comments: comments_for(@post),
        comments_url: comments_url,
        post_id: @post.id,
        signed_in: current_user.present?,
        login: current_user.try(:login),
        gravathar: current_user.present? ? gravathar(current_user.email) : '',
        post_url: post_path(@post)
      }
  end


  private
    def gravathar(email)
      "https://secure.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
    end
      
    def set_post
      @post = Post.where(permalink: params[:id]).first
    end

    def comments_for(post)
      post.comments.map{ |comment|
        {
          id: comment.id,
          created_at: comment.created_at.strftime('%d %B %Y'),
          text: comment.text,
          gravathar: gravathar(comment.user.email),
          email: comment.user.email,
          login: comment.user.login
        }
      }

    end
end

app/controllers/signup_controller.rb
class SignupController < Devise::RegistrationsController

	def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/_form.html.haml
= form_for [:admin, @post] do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/admin/posts/edit.html.haml
%h1 Edit post

= render 'form'

= link_to 'Back', posts_path

app/views/admin/posts/index.html.haml
= react_component 'AdminPosts', {posts: @props, url: admin_posts_path}, {}

app/views/admin/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/admin/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Body:
  = @post.body

= link_to 'Edit', edit_admin_post_path(@post)
\|
= link_to 'Back', admin_posts_path

app/views/layouts/_navbar.html.haml
.nav
  - if @post
    .item.pull-left.home-link
      = link_to "Home", root_path
  .item.pull-right
    - if current_user
      = link_to('Logout', destroy_user_session_path, :method => :delete)
    - else
      = link_to('Login', new_user_session_path)
  .item.pull-right 
    -unless current_user
      = link_to('Register', new_user_registration_path)

  .clearfix

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.haml
= react_component 'Posts',{posts: @props},{}

app/views/posts/show.html.haml
= react_component 'Post', @props,{}

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path